name: Node Lambda Deployment with Github Action

on:
  push:
    branches:
      - 'main'

jobs:
  build:
    runs-on: 'ubuntu-latest'
    strategy:
      matrix:
        node-version: [16.x]
    steps:
      - name: ğŸ£ Checking out project
        uses: actions/checkout@v3
        with:
          node-version: 16
          cache: 'npm'
          cache-dependency-path: ./package-lock.json

      - name: ğŸ£ Setup node environment
        uses: actions/setup-node@v1
        with:
          node-version: '14.x'
          
      - name: ğŸ’» Install serverless globally
        run: npm install -g serverless
      
      - name: â˜ï¸ Configure serverless authentication
        run: sls config credentials --provider aws --key ${{ secrets.AWS_ACCESS_KEY_ID }} --secret ${{ secrets.AWS_SECRET_ACCESS_KEY }}

      - name: ğŸ’» Install project
        run: npm ci
     
      - name: ğŸš€ Deploy lambda function
        run: sls deploy